import Foundation

struct LocalizedString {
//    MARK: - Common
    static let home = NSLocalizedString("common_home", comment: "home")
    static let topPosters = NSLocalizedString("common_top_posters", comment: "top posters")
    static let ok = NSLocalizedString("common_ok", comment: "ok")
    static let `continue` = NSLocalizedString("common_continue", comment: "continue")
    static let username = NSLocalizedString("common_username", comment: "username")
    static let color = NSLocalizedString("common_color", comment: "color")
    static let done = NSLocalizedString("common_done", comment: "done")
    static let next = NSLocalizedString("common_next", comment: "next")
    static let cancel = NSLocalizedString("common_cancel", comment: "cancel")
    static let skip = NSLocalizedString("common_skip", comment: "skip")
    static let error = NSLocalizedString("common_error", comment: "error")
    static let cameraRoll = NSLocalizedString("common_camera_roll", comment: "camera roll")
    static let post = NSLocalizedString("common_post", comment: "post")
    static let comments = NSLocalizedString("common_comments", comment: "comments")
    static let games = NSLocalizedString("common_games", comment: "games")
    static let rank = NSLocalizedString("common_rank", comment: "rank")
    static let views = NSLocalizedString("common_views", comment: "views")
    static let likes = NSLocalizedString("common_likes", comment: "likes")
    static let videos = NSLocalizedString("common_videos", comment: "videos")
    static let subscribe = NSLocalizedString("common_subscribe", comment: "subscribe")
    static let subscribed = NSLocalizedString("common_subscribed", comment: "subscribed")
    static let subscriber = NSLocalizedString("common_subscriber", comment: "subscriber")
    static let subscribers = NSLocalizedString("common_subscribers", comment: "subscribers")
    static let subscribing = NSLocalizedString("common_subscribing", comment: "subscribing")
    static let settings = NSLocalizedString("common_settings", comment: "settings")
    static let community = NSLocalizedString("common_community", comment: "community")
    static let socialNetworks = NSLocalizedString("common_social_networks", comment: "social networks")
    static let appIcon = NSLocalizedString("common_app_icon", comment: "app icon")
    static let classic = NSLocalizedString("common_classic", comment: "classic")
    static let gold = NSLocalizedString("common_gold", comment: "gold")
    static let secret = NSLocalizedString("common_secret", comment: "secret")
    static let connect = NSLocalizedString("common_connect", comment: "connect")
    static let itunesLibrary = NSLocalizedString("common_itunes_library", comment: "iTunes Library")
    static let songs = NSLocalizedString("common_songs", comment: "songs")
    static let artists = NSLocalizedString("common_artists", comment: "artists")
    static let add = NSLocalizedString("common_add", comment: "add")
    static let more = NSLocalizedString("common_more", comment: "more")
    static let other = NSLocalizedString("common_other", comment: "other")
    static let trash = NSLocalizedString("common_trash", comment: "trash")
    static let pick = NSLocalizedString("common_pick", comment: "pick")
    static let new = NSLocalizedString("common_new", comment: "new")
    static let phone = NSLocalizedString("common_phone", comment: "phone")
    static let email = NSLocalizedString("common_email", comment: "email")
    static let show = NSLocalizedString("common_show", comment: "show")
    static let hide = NSLocalizedString("common_hide", comment: "hide")
    static let password = NSLocalizedString("common_password", comment: "password")
    static let user = NSLocalizedString("common_user", comment: "user")
    static let users = NSLocalizedString("common_users", comment: "users")
    static let trending = NSLocalizedString("common_trending", comment: "trending")
    static let recent = NSLocalizedString("common_recent", comment: "recent")
    static let firstPosts = NSLocalizedString("common_first_posts", comment: "first posts")
    static let search = NSLocalizedString("common_search", comment: "search")
    static let options = NSLocalizedString("common_options", comment: "options")
    static let notifications = NSLocalizedString("common_notifications", comment: "notifications")
    static let go = NSLocalizedString("common_go", comment: "go")
    static let gameRequests = NSLocalizedString("common_game_requests", comment: "game requests")
    static let friends = NSLocalizedString("common_friends", comment: "friends")
    static let dismiss = NSLocalizedString("common_dismiss", comment: "dismiss")
    static let accept = NSLocalizedString("common_accept", comment: "accept")

//    MARK: - Alert
    static let share = NSLocalizedString("alert_share", comment: "The share action")
    static let delete = NSLocalizedString("alert_delete", comment: "The delete action")
    static let exit = NSLocalizedString("alert_exit", comment: "The exit action")
    static let startOver = NSLocalizedString("alert_start_over", comment: "The start over action")
    static let draft = NSLocalizedString("alert_draft", comment: "The draft action")
    static let draftMessage = NSLocalizedString("alert_draft_message", comment: "The draft message")
    static let oops = NSLocalizedString("alert_oops", comment: "The oops action")
    static let oopsMessage = NSLocalizedString("alert_oops_message", comment: "The oops message")
    static let emailTitle = NSLocalizedString("alert_email_title", comment: "The title of email message")
    static let emailMessage = NSLocalizedString("alert_email_message", comment: "The email message")
    static let block = NSLocalizedString("alert_block", comment: "The block action")
    static let blockUser = NSLocalizedString("alert_block_message", comment: "The message of block user")
    static let report = NSLocalizedString("alert_report", comment: "The report action")
    static let reportUser = NSLocalizedString("alert_report_message_user", comment: "The message of report user")
    static let reportPost = NSLocalizedString("alert_report_message_post", comment: "The message of report post")
    static let logOut = NSLocalizedString("alert_log_out", comment: "The log out action")
    static let goSettings = NSLocalizedString("alert_go_settings", comment: "The go settings action")
    static let alertOops = NSLocalizedString("alert_oops", comment: "The message of oops alert")
    static let terms = NSLocalizedString("alert_terms", comment: "The terms action")
    static let privacy = NSLocalizedString("alert_privacy", comment: "The privacy action")
    static let communityGuidelines = NSLocalizedString("alert_community_guidelines", comment: "The community guidelines action")

//    MARK: - Sign
    static let signTitle = NSLocalizedString("sign_title", comment: "The title of the sign window")
    static let signGoogle = NSLocalizedString("sign_google", comment: "The title of the google button")
    static let signUpButton = NSLocalizedString("sign_up_button", comment: "The title of the sign up button")
    static let signInButton = NSLocalizedString("sign_in_button", comment: "The title of the sign in button")
    static let signChart = NSLocalizedString("sign_chart", comment: "The label of the chart")
    static let signTerms = NSLocalizedString("sign_terms", comment: "The title of terms link")
    static let signPrivacy = NSLocalizedString("sign_privacy", comment: "The title of privacy policies link")
    static let signCommunity = NSLocalizedString("sign_community", comment: "The title of community guidelines link")
    static let signUpUsernameTitle = NSLocalizedString("sign_up_username_title", comment: "The title of the sign up window")
    static let signUpUsernameWarning = NSLocalizedString("sign_up_username_warning", comment: "The warning label of the sign up window")
    static let signUpUsernameWarningLong = NSLocalizedString("sign_up_username_warning_long", comment: "The long warning label of the sign up window")
    static let signUpCode = NSLocalizedString("sign_up_code", comment: "The title of the verification code window")
    static let signUpPasswordTitle = NSLocalizedString("sign_up_password_title", comment: "The title of the new password window")
    static let signUpPasswordSubTitle = NSLocalizedString("sign_up_password_subtitle", comment: "The subtitle of the new password window")
    static let signUpPasswordForgot = NSLocalizedString("sign_up_password_forgot", comment: "The title of the forgot button")
    static let signUpPasswordAlertTitle = NSLocalizedString("sign_up_password_alert_title", comment: "The title of the alert password")
    static let signUpPasswordAlertMessage = NSLocalizedString("sign_up_password_alert_message", comment: "The message of the alert password")
    
//    MARK: - Top Posters
    static let topPostersGlobal = NSLocalizedString("top_posters_global", comment: "The title of the global cell")
    static let topPostersVideos = NSLocalizedString("top_posters_videos", comment: "The counter of videos")

//    MARK: - Profile
    static let profileBecome = NSLocalizedString("profile_become", comment: "The title of the become label")
    static let profileNoRank = NSLocalizedString("profile_no_rank", comment: "The title of no ranked user")
    static let profileSubscribersZero = NSLocalizedString("profile_subscribers_zero", comment: "The counter of 0 subscribers")
    static let profileSubscribersOne = NSLocalizedString("profile_subscribers_one", comment: "The counter of 1 subscriber")
    static let profileSubscribers = NSLocalizedString("profile_subscribers", comment: "The counter of subscribers")
    static let profileSubscribersK = NSLocalizedString("profile_subscribers_k", comment: "The counter of k subscribers")
    static let profileSubscribing = NSLocalizedString("profile_subscribing", comment: "The counter of subscribing")
    static let profileEditProfile = NSLocalizedString("profile_button_edit", comment: "The title of the edit profile button")
    static let profileBio = NSLocalizedString("profile_bio", comment: "biography")
    static let profileBioPlaceholder = NSLocalizedString("profile_bio_placeholder", comment: "The placeholder of the biography")
    static let profileBioTitle = NSLocalizedString("profile_bio_title", comment: "The title of the bio composer")
    static let profileUsernameTitle = NSLocalizedString("profile_username_title", comment: "The title of the username composer")
    static let profileSocialPlaceholder = NSLocalizedString("profile_social_placeholder", comment: "The placeholder to mention user's social network")
    static let profileColorPickerTitle = NSLocalizedString("profile_color_title", comment: "The title of the color picker")
    static let profilePostPlaceholder = NSLocalizedString("profile_post_placeholder", comment: "The title of the post placeholder")
    static let profilePreferences = NSLocalizedString("profile_preferences", comment: "The title of the preferences header")
    static let profilePreferencesAdd = NSLocalizedString("profile_preferences_add", comment: "The title of add games cell")
    static let profilePreferencesConsole = NSLocalizedString("profile_preferences_console", comment: "The title of the add console")
    static let profilePreferencesGames = NSLocalizedString("profile_preferences_games", comment: "The title of the add games")
    static let profilePreferencesSubtitle = NSLocalizedString("profile_preferences_subtitle", comment: "The subtitle of the add preferences")
    static let profilePreferencesContinue = NSLocalizedString("profile_preferences_continue", comment: "The title of button continue")
    static let profileStatistics = NSLocalizedString("profile_statistics", comment: "The title of the statistics header")
    static let profileSettingsInstagramFollowUs = NSLocalizedString("profile_settings_instagram_follow_us", comment: "Ask the user if he want to follow us on instagram")
    static let profileSettingsDiscord = NSLocalizedString("profile_settings_discord", comment: "The title of discord button")
    static let profileSettingsFeedback = NSLocalizedString("profile_settings_feedback", comment: "The title of feedback button")
    static let profileSettingsJoin = NSLocalizedString("profile_settings_join", comment: "The title of join button")
    static let profileInvitationButton = NSLocalizedString("profile_invitation_button", comment: "The title of invitation button")
    static let profileInvitationPlaceholder = NSLocalizedString("profile_invitation_placeholder", comment: "The placeholder of invitation text field")
    static let profileInvitationHeaderGame = NSLocalizedString("profile_invitation_header_game", comment: "The header of game section")
    static let profileInvitationHeaderVideo = NSLocalizedString("profile_invitation_header_video", comment: "The header of video section")

//    MARK: - Post
    static let postComments = NSLocalizedString("post_comments", comment: "The counter of comments")
    static let postAdd = NSLocalizedString("post_add", comment: "The placeholder of comment")
    static let postUnknown = NSLocalizedString("post_unknown", comment: "The unknown username")
    static let postView = NSLocalizedString("post_view", comment: "To view other posts")
    static let postFollowButton = NSLocalizedString("post_follow_button", comment: "Post follow button")
    static let postCaption = NSLocalizedString("post_caption", comment: "The placeholder of caption")
    static let postSaveToCameraRoll = NSLocalizedString("save_to_camera_roll", comment: "The title of the save to camera roll button")
    static let postSaveWithWatermark = NSLocalizedString("save_with_watermark", comment: "The title of the save with watermark button")
    static let postSaveWithoutWatermark = NSLocalizedString("save_without_watermark", comment: "The title of the save without watermark button")
    static let postShareWithWatermark = NSLocalizedString("share_with_watermark", comment: "The title of the share with watermark button")
    static let postShareWithoutWatermark = NSLocalizedString("share_without_watermark", comment: "The title of the share without watermark button")

//    MARK: - Media Picker
    static let mediaPickerImageTitle = NSLocalizedString("media_picker_image_title", comment: "The title of the image media picker")
    static let mediaPickerVideoTitle = NSLocalizedString("media_picker_video_title", comment: "The title of the video media picker")
    static let mediaPickerMultiple = NSLocalizedString("media_picker_multiple", comment: "The title of the done button with the selection counter")
    static let mediaPickerMusicTitle = NSLocalizedString("media_picker_music_title", comment: "The title of the music media picker")
    static let mediaPickerSelectMultiple = NSLocalizedString("media_picker_select_multiple", comment: "The title of the select multiple button")
    static let mediaPickerSelectSingle = NSLocalizedString("media_picker_select_single", comment: "The title of the select single button")
    
//    MARK: - Date Abbreviation
    static let dateSecond = NSLocalizedString("date_second", comment: "%d with the abbreviation of second")
    static let dateMinute = NSLocalizedString("date_minute", comment: "%d with the abbreviation of minute")
    static let dateHour = NSLocalizedString("date_hour", comment: "%d with the abbreviation of hour")
    static let dateDay = NSLocalizedString("date_day", comment: "%d with the abbreviation of day")
    static let dateWeek = NSLocalizedString("date_week", comment: "%d with the abbreviation of week")
    static let dateMonth = NSLocalizedString("date_month", comment: "%d with the abbreviation of month")
    static let dateYear = NSLocalizedString("date_year", comment: "%d with the abbreviation of year")

//    MARK: - Badge
    static let badgeStreakTitle = NSLocalizedString("badge_streak_title", comment: "The title of streak badge")
    static let badgeStreakSubtitle = NSLocalizedString("badge_streak_subtitle", comment: "The subtitle of streak badge")
    static let badgeStreakRewardTitle = NSLocalizedString("badge_streak_reward_title", comment: "The title of streak reward")
    static let badgeStreakRewardSubtitle = NSLocalizedString("badge_streak_reward_subtitle", comment: "The subtitle of streak reward")
    static let badgeStreakRewardButton = NSLocalizedString("badge_streak_reward_button", comment: "The title button of streak reward")
    static let badgeAlphaTitle = NSLocalizedString("badge_alpha_title", comment: "The title of alpha badge")
    static let badgeAlphaSubtitle = NSLocalizedString("badge_alpha_subtitle", comment: "The subtitle of alpha badge")
    static let badgeBetaTitle = NSLocalizedString("badge_beta_title", comment: "The title of beta badge")
    static let badgeBetaSubtitle = NSLocalizedString("badge_beta_subtitle", comment: "The subtitle of beta badge")
    static let badgeAdminTitle = NSLocalizedString("badge_admin_title", comment: "The title of admin badge")
    static let badgeAdminSubtitle = NSLocalizedString("badge_admin_subtitle", comment: "The subtitle of admin badge")
    static let badgeModTitle = NSLocalizedString("badge_mod_title", comment: "The title of mod badge")
    static let badgeModSubtitle = NSLocalizedString("badge_mod_subtitle", comment: "The subtitle of mod badge")
    static let badgeTopPostersTitle = NSLocalizedString("badge_top_posters_title", comment: "The title of top posters badge")
    static let badgeTopPostersSubtitle = NSLocalizedString("badge_top_posters_subtitle", comment: "The subtitle of top posters badge")
    static let badgeContributorTitle = NSLocalizedString("badge_contributor_title", comment: "The title of contributor badge")
    static let badgeContributorSubtitle = NSLocalizedString("badge_contributor_subtitle", comment: "The subtitle of contributor badge")
    static let badgeSuperContributorTitle = NSLocalizedString("badge_super_contributor_title", comment: "The title of super contributor badge")
    static let badgeSuperContributorSubtitle = NSLocalizedString("badge_super_contributor_subtitle", comment: "The subtitle of super contributor badge")
    static let badgeMagicianTitle = NSLocalizedString("badge_magician_title", comment: "The title of magician badge")
    static let badgeMagicianSubtitle = NSLocalizedString("badge_magician_subtitle", comment: "The subtitle of magician badge")

//    MARK: - Import
    static let importPS4 = NSLocalizedString("import_ps4", comment: "The title for the ps4 importation")
    static let importPS4Subtitle = NSLocalizedString("import_ps4_subtitle", comment: "The subtitle for the ps4 importation")
    static let importSwitch = NSLocalizedString("import_switch", comment: "The title for the nintendo switch importation")
    static let importSwitchSubtitle = NSLocalizedString("import_switch_subtitle", comment: "The subtitle for the switch importation")
    static let importConnect = NSLocalizedString("import_connect", comment: "The title of the connect button")
    static let importNoGame = NSLocalizedString("import_no_game", comment: "The label when no game found")
    static let importDownloading = NSLocalizedString("import_downloading", comment: "The title when downloading")
    static let importSaveToCameraRoll = NSLocalizedString("import_save", comment: "The title when saved to camera roll")
    static let importSaveSuccessMessage = NSLocalizedString("import_save_success", comment: "The title when save sucess")

//    MARK: - Share
    static let shareContactTitle = NSLocalizedString("share_contact_title", comment: "The title of contact on share pop up")
    static let shareContactSubtitle = NSLocalizedString("share_contact_subtitle", comment: "The subtitle of contact on share pop up")
    static let shareContactButton = NSLocalizedString("share_contact_button", comment: "The title of button on share pop up")
    static let shareContactPlaceholder = NSLocalizedString("share_contact_placeholder", comment: "The placeholder of search bar on share pop up")
    
//    MARK: - Template
    static let templateTitle = NSLocalizedString("template_title", comment: "The title of the template")
    static let templateTwoTitle = NSLocalizedString("template_two_title", comment: "The title of the second template")

//    MARK: - Xbox Empty Clips
    static let xboxNoCapture = NSLocalizedString("xbox_no_capture", comment: "The message of when no capture available")
    static let xboxHelp = NSLocalizedString("xbox_help", comment: "The title of help button")

    
//    MARK: - Modal pop up
    static let modalXboxTitle = NSLocalizedString("modal_xbox_title", comment: "The title of xbox modal")
    static let modalXboxSubtitle = NSLocalizedString("modal_xbox_subtitle", comment: "The subtitle of xbox modal")
    static let modalXboxPlaceholder = NSLocalizedString("modal_xbox_placeholder", comment: "The placeholder of xbox modal")
    static let modalXboxErrorTitle = NSLocalizedString("modal_xbox_error_title", comment: "The title of xbox error modal")
    static let modalXboxErrorSubtitle = NSLocalizedString("modal_xbox_error_subtitle", comment: "The subtitle of xbox error modal")
    static let modalSoonTitle = NSLocalizedString("modal_soon_title", comment: "The title of coming soon modal")
    static let modalSoonSubtitle = NSLocalizedString("modal_soon_subtitle", comment: "The subtitle of coming soon modal")

//    MARK: - Toaster
    static let toasterPublishing = NSLocalizedString("toaster_publishing", comment: "The publishing message")
    static let toasterPublished = NSLocalizedString("toaster_published", comment: "The published message")
    static let toasterDownloading = NSLocalizedString("toaster_downloading", comment: "The downloading message")
    static let toasterFail = NSLocalizedString("toaster_fail", comment: "The fail message")
    
//    MARK: - Discord Pop Up
    static let discordTitle = NSLocalizedString("discord_title", comment: "The title of the pop up")
    static let discordSubtitleStart = NSLocalizedString("discord_subtitle_start", comment: "The start of the subtitle")
    static let discordSubtitleEnd =  NSLocalizedString("discord_subtitle-end", comment: "The end of the subtitle")
    static let discordTertiaryStart = NSLocalizedString("discord_tertiary_start", comment: "The start of the tertiary title")
    static let discordTertiaryEnd = NSLocalizedString("discord_tertiary_end", comment: "The end of the tertiary title")
    static let discordButton = NSLocalizedString("discord_button", comment: "The title of the button")
    
//    MARK: - Request
    static let requestContactTitle = NSLocalizedString("request_contact_title", comment: "The request contact title")
    static let requestContactMessage = NSLocalizedString("request_contact_message", comment: "The request contact message")
    static let requestPhotoTitle = NSLocalizedString("request_photo_title", comment: "The request photo title")
    static let requestPhotoMessage = NSLocalizedString("request_photo_message", comment: "The request photo message")
    static let requestCameraTitle = NSLocalizedString("request_camera_title", comment: "The request camera title")
    static let requestCameraMessage = NSLocalizedString("request_camera_message", comment: "The request camera message")
    static let requestRecordTitle = NSLocalizedString("request_record_title", comment: "The request record title")
    static let requestRecordMessage = NSLocalizedString("request_record_message", comment: "The request record message")
    static let requestITunesTitle = NSLocalizedString("request_itunes_title", comment: "The request iTunes title")
    static let requestITunesMessage = NSLocalizedString("request_itunes_message", comment: "The request iTunes message")
    static let requestTooManyClipMessage = NSLocalizedString("request_too_many_clip_message", comment: "10 videos max for best performance")
    
//    MARK: - Editor Error
    static let editorErrorShader = NSLocalizedString("editor_error_shader", comment: "The error message for shader")
    static let editorErrorTrack = NSLocalizedString("editor_error_track", comment: "The error message for track")
    static let editorTooManyClipErrorMessage = NSLocalizedString("editor_too_many_clip_error_message", comment: "The error message for too many cut")
    
//    MARK: - Editor Action
    static let editorActionShader = NSLocalizedString("editor_action_shader", comment: "The title of shader editor action")
    static let editorActionMusic = NSLocalizedString("editor_action_music", comment: "The title of music editor action")
    static let editorActionText = NSLocalizedString("editor_action_text", comment: "The title of text editor action")
    static let editorActionSticker = NSLocalizedString("editor_action_sticker", comment: "The title of sticker editor action")
    static let editorActionRecord = NSLocalizedString("editor_action_record", comment: "The title of record editor action")
    static let editorActionSFX = NSLocalizedString("editor_action_sfx", comment: "The title of sfx editor action")
    static let editorActionGIF = NSLocalizedString("editor_action_gif", comment: "The title of gif editor action")
    static let editorActionOverlay = NSLocalizedString("editor_action_overlay", comment: "The title of overlay editor action")
    static let editorActionCut = NSLocalizedString("editor_action_cut", comment: "The title of cut editor action")
    static let editorActionZoom = NSLocalizedString("editor_action_zoom", comment: "The title of zoom editor action")
    static let editorActionSpeed = NSLocalizedString("editor_action_speed", comment: "The title of speed editor action")
    static let editorActionShake = NSLocalizedString("editor_action_shake", comment: "The title of shake editor action")
    static let editorActionReverse = NSLocalizedString("editor_action_reverse", comment: "The title of reverse editor action")
    static let editorActionDelete = NSLocalizedString("editor_action_delete", comment: "The title of delete editor action")
    static let editorActionFilter = NSLocalizedString("editor_action_filter", comment: "The title of filter editor action")
    static let editorActionResize = NSLocalizedString("editor_action_resize", comment: "The title of resize editor action")
    static let editorActionEditText = NSLocalizedString("editor_action_edit_text", comment: "The title of edit text editor action")
    static let editorActionColor = NSLocalizedString("editor_action_color", comment: "The title of color editor action")
    static let editorActionFont = NSLocalizedString("editor_action_font", comment: "The title of font editor action")
    static let editorActionEditVideo = NSLocalizedString("editor_action_edit video", comment: "The title of edit video editor action")
    static let editorActionHighlight = NSLocalizedString("editor_action_highlight", comment: "The title of highlight editor action")
    static let editorActionTransition = NSLocalizedString("editor_action_transition", comment: "The title of transition editor action")
    static let editorActionMedia = NSLocalizedString("editor_action_media", comment: "The title of media editor action")
    static let editorActionImage = NSLocalizedString("editor_action_image", comment: "The title of image editor action")
    static let editorActionMute = NSLocalizedString("editor_action_mute", comment: "The title of mute editor action")
    static let editorActionUnmute = NSLocalizedString("editor_action_unmute", comment: "The title of unmute editor action")
    static let editorActionVolume = NSLocalizedString("editor_action_volume", comment: "The title of volume editor action")
    
//    MARK: - Editor Action Highlight
    static let editorActionHighlightAdd = NSLocalizedString("editor_action_highlight_add", comment: "The counter of highlights")

//    MARK: - Editor Action Music
    static let editorMusicTitle = NSLocalizedString("editor_music_title", comment: "The title of music action")
    static let editorMusicButtonCameraRoll = NSLocalizedString("editor_music_button_camera_roll", comment: "The title of camera roll button")
    static let editorMusicTracks = NSLocalizedString("editor_music_tracks", comment: "The counter of tracks")
    static let editorMusicSearchSongs = NSLocalizedString("editor_music_search_songs", comment: "The placeholder for songs on iTunes Library view")
    static let editorMusicSearchArtists = NSLocalizedString("editor_music_search_artists", comment: "The placeholder for artists on iTunes Library view")
    static let editorMusicBestOf = NSLocalizedString("editor_music_best_of", comment: "The title of best of tag")
    static let editorMusicPulse = NSLocalizedString("editor_music_pulse", comment: "The title of pulse tag")
    static let editorMusicUrban = NSLocalizedString("editor_music_urban", comment: "The title of urban tag")
    static let editorMusicCinematic = NSLocalizedString("editor_music_cinematic", comment: "The title of cinematic tag")
    static let editorMusicPop = NSLocalizedString("editor_music_pop", comment: "The title of pop tag")
    static let editorMusicFun = NSLocalizedString("editor_music_fun", comment: "The title of fun tag")
    static let editorMusicArcade = NSLocalizedString("editor_music_arcade", comment: "The title of arcade tag")
    static let editorMusicFight = NSLocalizedString("editor_music_fight", comment: "The title of fight tag")
    static let editorMusicMotor = NSLocalizedString("editor_music_motor", comment: "The title of motor tag")
    static let editorMusicScary = NSLocalizedString("editor_music_scary", comment: "The title of scary tag")
    static let editorMusicSciFi = NSLocalizedString("editor_music_sci_fi", comment: "The title of sci-fi tag")
    static let editorMusicMonster = NSLocalizedString("editor_music_monster", comment: "The title of monster tag")
    static let editorMusicUplifting = NSLocalizedString("editor_music_uplifting", comment: "The title of uplifting tag")
    static let editorMusicPro = NSLocalizedString("editor_music_pro", comment: "The title of pro tag")

//    MARK: - Editor Action FaceCam
    static let editorFaceCamTitle = NSLocalizedString("editor_facecam_title", comment: "The title of facecam action")
    static let editorFaceCamAdd = NSLocalizedString("editor_facecam_add", comment: "The title of button add to clip")
    static let editorFaceCamRetake = NSLocalizedString("editor_facecam_retake", comment: "The title of button retake")

//    MARK: - Editor Action Recorder
    static let editorRecorderTitle = NSLocalizedString("editor_recorder_title", comment: "The title of recorder action")
    static let editorRecorderSubtitle = NSLocalizedString("editor_recorder_subtitle", comment: "The subtitle button when no recording")
    static let editorRecorderSubtitleStop = NSLocalizedString("editor_recorder_subtitle_stop", comment: "The subtitle button when recording")
    static let editorRecorderSubtitleFailed = NSLocalizedString("editor_recorder_subtitle_failed", comment: "The subtitle button when recording failed")
    static let editorRecorderDefaultName = NSLocalizedString("editor_recorder_default_name", comment: "The default name of a recording")
    static let editorRecorderAdd = NSLocalizedString("editor_recorder_add", comment: "The title of button add to clip")
    
//    MARK: - Editor Action SFX
    static let editorSFXTitle = NSLocalizedString("editor_music_title", comment: "The title of music action")
    static let editorSFXAnimals = NSLocalizedString("editor_sfx_animals", comment: "The title of animals tag")
    static let editorSFXArcade = NSLocalizedString("editor_sfx_arcade", comment: "The title of arcade tag")
    static let editorSFXBeeps = NSLocalizedString("editor_sfx_beeps", comment: "The title of beeps tag")
    static let editorSFXCartoon = NSLocalizedString("editor_sfx_cartoon", comment: "The title of cartoon tag")
    static let editorSFXFear = NSLocalizedString("editor_sfx_fear", comment: "The title of fear tag")
    static let editorSFXHorns = NSLocalizedString("editor_sfx_horns", comment: "The title of horns tag")
    static let editorSFXImpacts = NSLocalizedString("editor_sfx_impacts", comment: "The title of impacts tag")
    static let editorSFXMagic = NSLocalizedString("editor_sfx_magic", comment: "The title of magic tag")
    static let editorSFXMemes = NSLocalizedString("editor_sfx_memes", comment: "The title of memes tag")
    static let editorSFXSciFi = NSLocalizedString("editor_sfx_sci_fi", comment: "The title of sci-fi tag")
    static let editorSFXGames = NSLocalizedString("editor_sfx_games", comment: "The title of games tag")
    static let editorSFXWhoosh = NSLocalizedString("editor_sfx_whoosh", comment: "The title of whoosh tag")
    static let editorSFXPro = NSLocalizedString("editor_sfx_pro", comment: "The title of pro tag")
    
//    MARK: - Editor Action Zoom
    static let editorZoomModify = NSLocalizedString("editor_zoom_modify", comment: "The label of zoom modify")
    static let editorZoomNoAnimation = NSLocalizedString("editor_no_animation", comment: "The label of no animation")
    static let editorZoomAnimationDuration = NSLocalizedString("editor_animation_duration", comment: "The label of animation duration in second")

//    MARK: - Editor Action Text
    static let editorTextPlaceholder = NSLocalizedString("editor_text_placeholder", comment: "The placeholder of text action")
    
//    MARK: - Snapchat Sticker
    static let snapchatSticker = NSLocalizedString("snapchat_sticker", comment: "The title of the snapchat sticker")

//    MARK: - Emotes
    static let openCameraRoll = NSLocalizedString("add_emote_open_camera_roll", comment: "Open Camera roll button when selecting emote as avatar")
    static let addEmoteTitle = NSLocalizedString("add_emote_title", comment: "Title of the add emote view controller")
    static let addEmoteSeeMore = NSLocalizedString("add_emote_see_more", comment: "Title of the add emote view controller")
    
//    MARK: - Notification
    static let notificationContributor = NSLocalizedString("notification_contributor", comment: "The title of the notification contributor")
    
//      MARK: - Clan
    static let clanCellTitle = NSLocalizedString("clan_cell_title", comment: "Clan cell title")
    static let clanCreateTitle = NSLocalizedString("create_clan_title", comment: "Create clan title")
    static let clanCreateSubtitle = NSLocalizedString("create_clan_subtitle", comment: "Create clan subtitle")
    static let clanCreateTertiary = NSLocalizedString("create_clan_tertiary", comment: "Create clan tertiary")
    static let clanCreateStatedButton = NSLocalizedString("create_clan_started_button", comment: "Started button title")
    static let clanCreateAddLogoButton = NSLocalizedString("create_clan_add_logo_button", comment: "Add Logo button title")
    static let clanCreateTitleName = NSLocalizedString("create_clan_title_name", comment: "Name view title")
    static let clanCreateTitleTag = NSLocalizedString("create_clan_title_tag", comment: "Tag view title")
    static let clanCreateTitleLogo = NSLocalizedString("create_clan_title_logo", comment: "Logo view title")
    static let clanCreateTitleColor = NSLocalizedString("create_clan_title_color", comment: "Color view title")
    static let clanCreateSubtitleName = NSLocalizedString("create_clan_subtitle_name", comment: "Name view subtitle")
    static let clanCreateSubtitleTag = NSLocalizedString("create_clan_subtitle_tag", comment: "Tag view subtitle")
    static let clanCreateSubtitleLogo = NSLocalizedString("create_clan_subtitle_logo", comment: "Logo view subtitle")
    static let clanCreateSubtitleColor = NSLocalizedString("create_clan_subtitle_color", comment: "Color view subtitle")
    static let clanSwitchTitle = NSLocalizedString("Switch Clan", comment: "Switch clan view title")
    static let clanSwitchSubtitle = NSLocalizedString("Active clan will be accessible", comment: "Switch clan view subtitle")
}
